/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.10.0.111.2 */
/* Module Version: 5.7 */
/* /usr/local/diamond/3.10_x64/ispfpga/bin/lin64/scuba -w -n clk_test -lang verilog -synth synplify -arch ep5g00p -type pll -fin 25 -fclkop 100 -fclkop_tol 0.0 -delay_cntl STATIC -fdel 0 -fb_mode CLOCKTREE -noclkos -fclkok 25 -fclkok_tol 0.0  */
/* Thu Mar 28 17:42:27 2019 */


`timescale 1 ns / 1 ps
module clk_test (CLK, RESET, CLKOP, CLKOK, LOCK)/* synthesis NGD_DRC_MASK=1 */;
    input wire CLK;
    input wire RESET;
    output wire CLKOP;
    output wire CLKOK;
    output wire LOCK;

    wire scuba_vlo;
    wire CLKOP_t;
    wire CLK_t;

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    // synopsys translate_off
    defparam PLLBInst_0.DELAY_CNTL = "STATIC" ;
    defparam PLLBInst_0.FDEL = "0" ;
    defparam PLLBInst_0.DUTY = "4" ;
    defparam PLLBInst_0.PHASEADJ = "0" ;
    defparam PLLBInst_0.CLKOK_DIV = "4" ;
    defparam PLLBInst_0.CLKOP_DIV = "8" ;
    defparam PLLBInst_0.CLKFB_DIV = "4" ;
    defparam PLLBInst_0.CLKI_DIV = "1" ;
    // synopsys translate_on
    EHXPLLB PLLBInst_0 (.RST(RESET), .CLKI(CLK_t), .CLKFB(CLKOP_t), .DDAMODE(scuba_vlo), 
        .DDAIZR(scuba_vlo), .DDAILAG(scuba_vlo), .DDAIDEL0(scuba_vlo), .DDAIDEL1(scuba_vlo), 
        .DDAIDEL2(scuba_vlo), .CLKOP(CLKOP_t), .CLKOK(CLKOK), .CLKOS(), 
        .LOCK(LOCK), .DDAOZR(), .DDAOLAG(), .DDAODEL0(), .DDAODEL1(), .DDAODEL2())
             /* synthesis DELAY_CNTL="STATIC" */
             /* synthesis FDEL="0" */
             /* synthesis DUTY="4" */
             /* synthesis PHASEADJ="0" */
             /* synthesis FB_MODE="CLOCKTREE" */
             /* synthesis FREQUENCY_PIN_CLKOP="100.000000" */
             /* synthesis FREQUENCY_PIN_CLKI="25.000000" */
             /* synthesis FREQUENCY_PIN_CLKOK="25.000000" */
             /* synthesis CLKOK_DIV="4" */
             /* synthesis CLKOP_DIV="8" */
             /* synthesis CLKFB_DIV="4" */
             /* synthesis CLKI_DIV="1" */
             /* synthesis FIN="25.000000" */;

    assign CLKOP = CLKOP_t;
    assign CLK_t = CLK;


    // exemplar begin
    // exemplar attribute PLLBInst_0 DELAY_CNTL STATIC
    // exemplar attribute PLLBInst_0 FDEL 0
    // exemplar attribute PLLBInst_0 DUTY 4
    // exemplar attribute PLLBInst_0 PHASEADJ 0
    // exemplar attribute PLLBInst_0 FB_MODE CLOCKTREE
    // exemplar attribute PLLBInst_0 FREQUENCY_PIN_CLKOP 100.000000
    // exemplar attribute PLLBInst_0 FREQUENCY_PIN_CLKI 25.000000
    // exemplar attribute PLLBInst_0 FREQUENCY_PIN_CLKOK 25.000000
    // exemplar attribute PLLBInst_0 CLKOK_DIV 4
    // exemplar attribute PLLBInst_0 CLKOP_DIV 8
    // exemplar attribute PLLBInst_0 CLKFB_DIV 4
    // exemplar attribute PLLBInst_0 CLKI_DIV 1
    // exemplar attribute PLLBInst_0 FIN 25.000000
    // exemplar end

endmodule
